### ISSUE TITLE
Task `mix shopifex.install` not working

### ISSUE THREAD

**Issue by nbernardes** [ericdude4/shopifex#67]
Hello 👋
On a new phoenix app, when I run `mix shopifex.install` fails with the following error

```elixir
== Compilation error in file lib/shopifex_web/views/error_helpers.ex ==
** (RuntimeError) use Phoenix.HTML is no longer supported in v4.0.

To keep compatibility with previous versions, add {:phoenix_html_helpers, "~> 1.0"} to your mix.exs deps
and then, instead of "use Phoenix.HTML", you might:

    import Phoenix.HTML
    import Phoenix.HTML.Form
    use PhoenixHTMLHelpers


    (phoenix_html 4.1.1) expanding macro: Phoenix.HTML.__using__/1
    lib/shopifex_web/views/error_helpers.ex:6: ShopifexWeb.ErrorHelpers (module)
    (elixir 1.16.2) expanding macro: Kernel.use/1
    lib/shopifex_web/views/error_helpers.ex:6: ShopifexWeb.ErrorHelpers (module)
```

**Comment by ericdude4** [comment]
Hi @nbernardes 👋 

Thanks for this report! I'm currently not using this library on any newer versions of Phoenix. All of my projects are still on 1.6 :/ 

Please feel free to open a PR for this and I will be happy to review. If you'd like, you should be able to follow the "manual installation" instructions: https://github.com/ericdude4/shopifex?tab=readme-ov-file#manual-installation

Eric

**Comment by nbernardes** [comment]
I'll see if I have some time to try and make it work on 1.7 versions and come up with a PR.

**Comment by ericdude4** [comment]
fixed in #71
